export const KEY_FILE_ID_LIST = 'app:fileIds'
export const KEY_MODULE_META = 'app:module_meta'
export const KEY_MODULE_MAPPING = 'app:module_mapping'
export const KEY_DISABLED_RULES = 'app:disabled_rules'
export const KEY_RULE_ORDER = 'app:rule_order'
export const KEY_FILE_PREFIX = 'file:'
