export { isFunctionExpression } from './isFunctionExpression'
export { isIIFE } from './isIIFE'
export { isTopLevel } from './isTopLevel'
export { renameFunctionParameters } from './renameFunctionParameters'
export { pruneComments } from './pruneComments'
