use std::collections::HashMap;

use wakaru_core::{
    recover_angular_components_from_js, recover_angular_components_from_modules,
    AngularModuleSource, AngularRecoveryCompleteness, AngularRecoveryOptions,
};

const RUNTIME: &str = include_str!("bundles/angular-ivy-gen/dist/runtime.js");
const MAIN: &str = include_str!("bundles/angular-ivy-gen/dist/main.js");
const LAZY: &str = include_str!("bundles/angular-ivy-gen/dist/lazy.js");
const CLOSURE_SIMPLE: &str = include_str!("bundles/angular-ivy-gen/dist/closure-simple.js");
const CLOSURE_ADVANCED: &str = include_str!("bundles/angular-ivy-gen/dist/closure-advanced.js");

fn assert_production_artifact(source: &str) {
    assert!(!source.contains("ɵsetClassMetadata"));
    assert!(!source.contains("template: `"));
    assert!(!source.contains("<article"));
}

#[test]
fn recovers_components_from_angular_cli_production_chunks() {
    assert_production_artifact(RUNTIME);
    assert_production_artifact(MAIN);
    assert_production_artifact(LAZY);

    let recovered = recover_angular_components_from_modules(
        &[
            AngularModuleSource {
                filename: "runtime.js",
                source: RUNTIME,
            },
            AngularModuleSource {
                filename: "main.js",
                source: MAIN,
            },
            AngularModuleSource {
                filename: "lazy.js",
                source: LAZY,
            },
        ],
        AngularRecoveryOptions::default(),
    )
    .expect("pinned Angular production chunks should parse");

    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();
    assert_eq!(by_selector.len(), 3);
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"]
        .source
        .contains("(click)=\"select()\" [disabled]=\"disabled\">Select</button>"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("@if (showDetails) {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<p class="details">{{ detail }}</p>"#));
    assert!(by_selector["fixture-card"].source.contains("@else {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ selectButton.disabled }}"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
    assert!(by_selector["fixture-card"]
        .source
        .contains("title = \"Generated by Angular\""));
    assert!(by_selector["app-root"]
        .source
        .contains("<span card-extra>Projected content</span>"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
}

#[test]
fn recovers_the_same_components_after_closure_simple() {
    assert_production_artifact(CLOSURE_SIMPLE);

    let recovered =
        recover_angular_components_from_js(CLOSURE_SIMPLE, AngularRecoveryOptions::default())
            .expect("pinned Closure output should parse");
    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();

    assert_eq!(by_selector.len(), 3);
    assert!(by_selector.contains_key("app-root"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"]
        .source
        .contains("@if (showDetails) {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
}

#[test]
fn recovers_components_after_rooted_closure_advanced() {
    assert_production_artifact(CLOSURE_ADVANCED);

    let recovered =
        recover_angular_components_from_js(CLOSURE_ADVANCED, AngularRecoveryOptions::default())
            .expect("pinned rooted Closure ADVANCED output should parse");
    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();

    assert_eq!(by_selector.len(), 3);
    assert!(by_selector.contains_key("app-root"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"].source.contains("@if ("));
    assert!(by_selector["fixture-card"].source.contains("@else {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
}
