use std::collections::HashMap;

use wakaru_core::{
    recover_angular_components_from_js, recover_angular_components_from_modules,
    AngularModuleSource, AngularRecoveryCompleteness, AngularRecoveryOptions,
};

const RUNTIME: &str = include_str!("bundles/angular-ivy-gen/dist/runtime.js");
const MAIN: &str = include_str!("bundles/angular-ivy-gen/dist/main.js");
const LAZY: &str = include_str!("bundles/angular-ivy-gen/dist/lazy.js");
const CLOSURE_SIMPLE: &str = include_str!("bundles/angular-ivy-gen/dist/closure-simple.js");
const CLOSURE_ADVANCED: &str = include_str!("bundles/angular-ivy-gen/dist/closure-advanced.js");
const CLOSURE_ADVANCED_STRUCTURAL: &str =
    include_str!("bundles/angular-ivy-gen/dist/closure-advanced-structural.js");
const TEMPLATE_CONSTRUCTS: &str =
    include_str!("bundles/angular-ivy-gen/dist/template-constructs.js");
const TEMPLATE_CONSTRUCTS_ASSIGNMENT: &str =
    include_str!("bundles/angular-ivy-gen/dist/template-constructs-assignment.js");

fn assert_production_artifact(source: &str) {
    assert!(!source.contains("ɵsetClassMetadata"));
    assert!(!source.contains("template: `"));
    assert!(!source.contains("<article"));
}

#[test]
fn recovers_components_from_angular_cli_production_chunks() {
    assert_production_artifact(RUNTIME);
    assert_production_artifact(MAIN);
    assert_production_artifact(LAZY);

    let recovered = recover_angular_components_from_modules(
        &[
            AngularModuleSource {
                filename: "runtime.js",
                source: RUNTIME,
            },
            AngularModuleSource {
                filename: "main.js",
                source: MAIN,
            },
            AngularModuleSource {
                filename: "lazy.js",
                source: LAZY,
            },
        ],
        AngularRecoveryOptions::default(),
    )
    .expect("pinned Angular production chunks should parse");

    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();
    assert_eq!(by_selector.len(), 3);
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"]
        .source
        .contains("(click)=\"select()\" [disabled]=\"disabled\">Select</button>"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("@if (showDetails) {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<p class="details">{{ detail }}</p>"#));
    assert!(by_selector["fixture-card"].source.contains("@else {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ selectButton.disabled }}"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
    assert!(by_selector["fixture-card"]
        .source
        .contains("title = \"Generated by Angular\""));
    assert!(by_selector["app-root"]
        .source
        .contains("<span card-extra>Projected content</span>"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
}

#[test]
fn recovers_the_same_components_after_closure_simple() {
    assert_production_artifact(CLOSURE_SIMPLE);

    let recovered =
        recover_angular_components_from_js(CLOSURE_SIMPLE, AngularRecoveryOptions::default())
            .expect("pinned Closure output should parse");
    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();

    assert_eq!(by_selector.len(), 3);
    assert!(by_selector.contains_key("app-root"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"]
        .source
        .contains("@if (showDetails) {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
}

#[test]
fn recovers_components_after_rooted_closure_advanced() {
    assert_production_artifact(CLOSURE_ADVANCED);

    let recovered =
        recover_angular_components_from_js(CLOSURE_ADVANCED, AngularRecoveryOptions::default())
            .expect("pinned rooted Closure ADVANCED output should parse");
    let by_selector = recovered
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();

    assert_eq!(by_selector.len(), 3);
    assert!(by_selector.contains_key("app-root"));
    assert!(by_selector.contains_key("fixture-lazy-card"));
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-card"].issues,
        by_selector["fixture-card"].source,
    );
    assert!(by_selector["fixture-card"].source.contains("@if ("));
    assert!(by_selector["fixture-card"].source.contains("@else {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("{{ title | uppercase }}"));
    assert!(by_selector["fixture-card"].source.contains("#selectButton"));
    assert!(by_selector["fixture-card"]
        .source
        .contains(r#"<ng-content select="[card-extra]" />"#));
}

#[test]
fn infers_structural_roles_after_minimally_rooted_closure_advanced() {
    assert_production_artifact(CLOSURE_ADVANCED_STRUCTURAL);
    assert!(CLOSURE_ADVANCED_STRUCTURAL.contains("ɵɵdefineComponent"));
    for omitted_role in [
        "ɵɵtext",
        "ɵɵtextInterpolate",
        "ɵɵtextInterpolate1",
        "ɵɵtemplate",
        "ɵɵconditional",
        "ɵɵgetCurrentView",
        "ɵɵnextContext",
        "ɵɵproperty",
        "ɵɵresetView",
        "ɵɵrestoreView",
    ] {
        assert!(
            !CLOSURE_ADVANCED_STRUCTURAL.contains(omitted_role),
            "structural fixture should not expose {omitted_role}"
        );
    }

    let report = wakaru_core::analyze_angular_components_from_js(
        CLOSURE_ADVANCED_STRUCTURAL,
        AngularRecoveryOptions::default(),
    )
    .expect("minimally rooted Closure ADVANCED output should parse");
    let by_selector = report
        .components
        .iter()
        .map(|component| (component.selector.as_str(), component))
        .collect::<HashMap<_, _>>();

    assert_eq!(by_selector.len(), 4);
    assert_eq!(
        by_selector["app-root"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["app-root"].issues,
        by_selector["app-root"].source,
    );
    assert!(by_selector["app-root"]
        .source
        .contains("<h1>{{ title }}</h1>"));
    assert_eq!(
        by_selector["fixture-lazy-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["fixture-lazy-card"].issues,
        by_selector["fixture-lazy-card"].source,
    );
    assert!(by_selector["fixture-lazy-card"]
        .source
        .contains("<aside>Lazy {{ message }}</aside>"));
    assert_eq!(
        by_selector["structural-view-card"].completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        by_selector["structural-view-card"].issues,
        by_selector["structural-view-card"].source,
    );
    assert!(by_selector["structural-view-card"]
        .source
        .contains("@if (visible) {"));
    assert!(by_selector["structural-view-card"]
        .source
        .contains("(click)=\"select()\""));
    assert!(by_selector["structural-view-card"]
        .source
        .contains("[disabled]=\"disabled\""));
    assert_eq!(
        by_selector["fixture-card"].completeness,
        AngularRecoveryCompleteness::Partial
    );
    assert_eq!(
        by_selector["fixture-card"]
            .source
            .matches("<p class=\"details\">")
            .count(),
        2
    );
    assert!(by_selector["fixture-card"]
        .source
        .contains("<p class=\"details\">Details hidden</p>"));
    assert!(by_selector["fixture-card"].source.contains("@if (cg) {"));
    assert!(by_selector["fixture-card"].source.contains("@else {"));
    assert!(by_selector["fixture-card"]
        .source
        .contains("[disabled]=\"disabled\""));
    assert_eq!(report.stats.malformed_instruction_calls, 0);
}

#[test]
fn recovers_flat_bindings_from_isolated_angular_compiler_output() {
    assert_production_artifact(TEMPLATE_CONSTRUCTS);

    let recovered =
        recover_angular_components_from_js(TEMPLATE_CONSTRUCTS, AngularRecoveryOptions::default())
            .expect("pinned Angular compiler output should parse");
    let component = recovered
        .iter()
        .find(|component| component.selector == "fixture-flat-bindings")
        .expect("flat binding component should recover");

    assert_eq!(
        component.completeness,
        AngularRecoveryCompleteness::Complete
    );
    assert!(component.source.contains(
        "<article title=\"Flat bindings\" (click)=\"activate($event)\" \
         [style.opacity]=\"opacity\" [class.active]=\"active\" \
         [attr.aria-label]=\"label\">"
    ));
    assert!(component
        .source
        .contains("<h2>{{ prefix }} {{ label }}</h2>"));
    assert!(component
        .source
        .contains("<input [disabled]=\"disabled\" />"));
}

#[test]
fn recovers_view_local_angular_template_constructs() {
    assert_production_artifact(TEMPLATE_CONSTRUCTS);
    for authored_template_fragment in ["@if", "@for", "<ng-content", "#row"] {
        assert!(
            !TEMPLATE_CONSTRUCTS.contains(authored_template_fragment),
            "generated fixture should not retain {authored_template_fragment}"
        );
    }
    for instruction in [
        "ɵɵconditionalCreate",
        "ɵɵrepeaterCreate",
        "ɵɵprojection",
        "ɵɵpipeBind1",
        "ɵɵreference",
    ] {
        assert!(
            TEMPLATE_CONSTRUCTS.contains(instruction)
                || TEMPLATE_CONSTRUCTS.contains(&instruction.replace('ɵ', "\\u0275")),
            "generated fixture should contain {instruction}"
        );
    }

    let recovered =
        recover_angular_components_from_js(TEMPLATE_CONSTRUCTS, AngularRecoveryOptions::default())
            .expect("pinned Angular compiler output should parse");
    let component = recovered
        .iter()
        .find(|component| component.selector == "fixture-structural-constructs")
        .expect("structural component identity should recover");

    assert_eq!(
        component.completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        component.issues,
        component.source,
    );
    assert!(component.source.contains("@if (showDetails) {"));
    assert!(component
        .source
        .contains("<h2>{{ title | uppercase }}</h2>"));
    assert!(component.source.contains("@else {"));
    assert!(component
        .source
        .contains("@for (item of items; track item.id) {"));
    assert!(component.source.contains("#row"));
    assert!(component.source.contains("(click)=\"select(row, item)\""));
    assert!(component.source.contains("{{ item.label }}"));
    assert!(component.source.contains("@empty {"));
    assert!(component.source.contains("<p>No items</p>"));
    assert!(component
        .source
        .contains(r#"<ng-content select="[card-footer]" />"#));
    assert!(!component.source.contains("ɵɵ"));
    assert_eq!(
        component.stats.runtime_calls_observed,
        component.stats.rendered_instruction_calls
    );
    assert_eq!(component.stats.unsupported_runtime_calls, 0);
    assert_eq!(component.stats.malformed_instruction_calls, 0);
}

#[test]
fn recovers_assignment_lowered_angular_template_constructs() {
    assert_production_artifact(TEMPLATE_CONSTRUCTS_ASSIGNMENT);
    assert!(TEMPLATE_CONSTRUCTS_ASSIGNMENT
        .contains("var FixtureStructuralConstructsComponent_Conditional_1_Template"));
    assert!(TEMPLATE_CONSTRUCTS_ASSIGNMENT
        .contains("FixtureStructuralConstructsComponent_Conditional_1_Template = function"));
    assert!(!TEMPLATE_CONSTRUCTS_ASSIGNMENT
        .contains("function FixtureStructuralConstructsComponent_Conditional_1_Template"));

    let recovered = recover_angular_components_from_js(
        TEMPLATE_CONSTRUCTS_ASSIGNMENT,
        AngularRecoveryOptions::default(),
    )
    .expect("assignment-lowered Angular compiler output should parse");
    let component = recovered
        .iter()
        .find(|component| component.selector == "fixture-structural-constructs")
        .expect("structural component identity should recover");

    assert_eq!(
        component.completeness,
        AngularRecoveryCompleteness::Complete,
        "issues: {:#?}\n{}",
        component.issues,
        component.source,
    );
    assert!(component.source.contains("@if (showDetails) {"));
    assert!(component
        .source
        .contains("@for (item of items; track item.id) {"));
    assert!(component.source.contains("(click)=\"select(row, item)\""));
    assert!(component.source.contains("@empty {"));
    assert!(component
        .source
        .contains(r#"<ng-content select="[card-footer]" />"#));
    assert_eq!(
        component.stats.runtime_calls_observed,
        component.stats.rendered_instruction_calls
    );
    assert_eq!(component.stats.unsupported_runtime_calls, 0);
    assert_eq!(component.stats.malformed_instruction_calls, 0);
}
