<script setup lang="ts">
import {
    Dialog,
    DialogPanel,
    DialogTitle,
    TransitionChild,
    TransitionRoot,
} from '@headlessui/vue'
import { refThrottled } from '@vueuse/core'
import { useAtom, useSetAtom } from 'jotai-vue'
import { useRoute, useRouter } from 'vue-router'
import { moduleMappingAtom, moduleMetaOverrideAtom, modulesAtom, prettifyAllModulesAtom, resetModulesAtom } from '../atoms/module'
import { disabledRuleIdsAtom } from '../atoms/rule'
import Card from '../components/Card.vue'
import CodemirrorEditor from '../components/CodemirrorEditor.vue'
import FileUpload from '../components/FileUpload.vue'
import Separator from '../components/Separator.vue'
import useState from '../composables/shared/useState'
import { decodeHash } from '../composables/url'
import { SharedDataVersion } from '../const'
import { unpack } from '../worker'
import type { TransformedModule } from '../types'

const INPUT_SIZE_WARNING = 1024 * 1024 * 5 // 5MB
const INPUT_SIZE_WARNING_MESSAGE = `The input file size exceeds ${INPUT_SIZE_WARNING / 1024 / 1024}MB. Processing may take longer and consume more memory than usual. If you experience an 'Out of Memory' error, please consider using the CLI for better performance.`

const route = useRoute()
const router = useRouter()

const [source] = useState('')
const [_isLoading, setIsLoading] = useState(false)
const isLoading = refThrottled(_isLoading, 300, true, false)

const setModules = useSetAtom(modulesAtom)
const setModuleMetaOverride = useSetAtom(moduleMetaOverrideAtom)
const [moduleMapping, setModuleMapping] = useAtom(moduleMappingAtom)
const setDisabledRuleIds = useSetAtom(disabledRuleIdsAtom)
const resetModules = useSetAtom(resetModulesAtom)
const prettifyAllModules = useSetAtom(prettifyAllModulesAtom)

onLoad()

function onLoad() {
    if (typeof route.hash === 'string' && route.hash.startsWith('#')) {
        const hash = route.hash.slice(1)
        const { version = 1, code, rules, mapping, meta } = decodeHash(hash)

        if (version !== SharedDataVersion) {
            // eslint-disable-next-line no-alert
            alert('The shared data is generated by an older version of Wakaru. Ir might not work as expected.')
        }

        resetModules()

        if (rules) setDisabledRuleIds(rules)
        if (mapping) setModuleMapping(mapping)
        if (meta) setModuleMetaOverride(meta)
        if (code) startUnpack(code)
    }
}

function onUpload(file: File) {
    const reader = new FileReader()
    reader.onload = (event) => {
        const scriptContent = event.target?.result
        if (!scriptContent || typeof scriptContent !== 'string') {
            // eslint-disable-next-line no-alert
            alert('Invalid file content')
            return
        }

        if (file.size > INPUT_SIZE_WARNING) {
            // eslint-disable-next-line no-alert
            alert(INPUT_SIZE_WARNING_MESSAGE)
        }

        resetModules()
        startUnpack(scriptContent)
    }
    reader.readAsText(file)
}

function onSubmit() {
    if (!source.value) return

    resetModules()
    startUnpack(source.value)
}

async function startUnpack(input: string) {
    setIsLoading(true)

    try {
        const { modules, moduleIdMapping } = await unpack(input)
        const _unpackedModules = modules.map<TransformedModule>((module) => {
            const { id, isEntry, code, tags } = module
            return {
                id,
                isEntry,
                code,
                transformed: code,
                import: module.import,
                export: module.export,
                tags,
            }
        })

        const unpackedModules = [
            ..._unpackedModules.filter(mod => mod.isEntry).sort((a, b) => +a.id - +b.id),
            ..._unpackedModules.filter(mod => !mod.isEntry).sort((a, b) => +a.id - +b.id),
        ]

        // avoid overriding the module mapping if it's already set
        // preserve the mapping from the URL hash
        if (Object.keys(moduleMapping).length === 0) {
            setModuleMapping(moduleIdMapping)
        }
        setModules(unpackedModules, [], [])

        // Run prettify in the background without blocking the main flow
        prettifyAllModules()

        const firstModule = unpackedModules[0]
        if (firstModule) {
            router.push({ name: 'file', params: { id: firstModule.id } })
        }
    }
    catch (error) {
        console.error(error)
        // eslint-disable-next-line no-alert
        alert('Failed to unpack the code. Please check the console and report the issue.')
    }
    finally {
        setIsLoading(false)
    }
}
</script>

<template>
    <Card
        title="Upload"
        description="You can either upload a source file or paste the code into the editor below."
    >
        <div class="flex flex-col w-full">
            <FileUpload accept=".txt,.js" @upload="onUpload" />

            <Separator>OR</Separator>

            <div class="flex-1">
                <CodemirrorEditor
                    v-model="source"
                    autofocus
                    :style="{
                        height: 'calc(100vh - 26rem)',
                    }"
                />
            </div>
            <div class="flex justify-center p-4">
                <button
                    class="flex w-fit bg-blue-600 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded transition"
                    @click="onSubmit"
                >
                    Start
                </button>
            </div>
        </div>
    </Card>

    <TransitionRoot appear :show="isLoading" as="template">
        <Dialog as="div" class="relative z-10">
            <TransitionChild
                as="template"
                enter="duration-300 ease-out"
                enter-from="opacity-0"
                enter-to="opacity-100"
                leave="duration-200 ease-in"
                leave-from="opacity-100"
                leave-to="opacity-0"
            >
                <div class="fixed inset-0 bg-black bg-opacity-25" />
            </TransitionChild>

            <div class="fixed inset-0 overflow-y-auto">
                <div
                    class="flex min-h-full items-center justify-center p-4 text-center"
                >
                    <TransitionChild
                        as="template"
                        enter="duration-300 ease-out"
                        enter-from="opacity-0 scale-95"
                        enter-to="opacity-100 scale-100"
                        leave="duration-200 ease-in"
                        leave-from="opacity-100 scale-100"
                        leave-to="opacity-0 scale-95"
                    >
                        <DialogPanel
                            class="w-full max-w-md transform overflow-hidden rounded-2xl bg-white p-6 text-left align-middle shadow-xl transition-all"
                        >
                            <DialogTitle
                                as="h3"
                                class="text-lg font-medium leading-6 text-gray-900"
                            >
                                Processing...
                            </DialogTitle>
                            <div class="mt-2" />
                        </DialogPanel>
                    </TransitionChild>
                </div>
            </div>
        </Dialog>
    </TransitionRoot>
</template>
