import { Component } from '@angular/core';

@Component({
  selector: 'fixture-card',
  template: `
    <article class="card">
      <h2>{{ title }}</h2>
      <button type="button" (click)="select()" [disabled]="disabled">Select</button>
    </article>
  `,
  styles: [
    `
      :host { display: block; }
      article { padding: 1rem; }
    `,
  ],
})
export class FixtureCardComponent {
  title = 'Generated by Angular';
  disabled = false;

  select() {
    this.disabled = true;
  }
}
